### PR TITLE
Massive improvement in broker startup time when using jdbc persistence

### PR DESCRIPTION
**Pull request by rhadoo**
Rewritten DELETE queries that run at broker startup. This way broker startup in a very crowded environment using an enhanced broker cluster is reduced from 3+hours to under 5 minutes.

### CODE REVIEW

**Comment by Cousjava** [comment]
This PR would be better raised in https://github.com/eclipse-ee4j/openmq which is the main repository of the OpenMQ project. However this likely not be accepted as it is not valid SQL on all databases: it will fail on MySQL for example.

**Comment by rhadoo** [comment]
I did not raise it on main repository as i have not received any replies to anything i have opened in the last 4 years on it , so i was hoping it would be possible to get it here . As for compatibility, it works on MySQL based engines, this being my exact use case, i did not have a means to effectively test for oracle , but the SQL should be valid.

**Comment by arjantijms** [comment]
>I did not raise it on main repository as i have not received any replies to anything i have opened in the last 4 years on it

The repo that @Cousjava mentioned only exists for a few months. It got moved there from the previous location. It's active at the moment.

I think that syntax like:

```
delete foo from foo
```

Might work only on MySQL and not on Postgres, H2, Derby, etc.

For this to work I think we would need to introduce dialects for supported databases, with a fallback for general SQL. In Postgres, `truncate` is often the faster alternative btw to delete all rows in a table, but this is a PG extension.

**Comment by rhadoo** [comment]
Thanks for the comments, i will check compatibility with all engines and open a PR on main if it works.
I expect the sql to still work on all, but bring improvements only on mysql derived engines. 
Truncate is the fastest way probably on all engines, but in a broker cluster you cannot use truncate, as tables will contain data belonging to other brokers.

**Pull request closed without merging**
